FROM golang:1.24.2

WORKDIR /chaas

COPY go.mod go.sum ./
RUN go mod download

COPY cache/ ./cache/
COPY master/ ./master/

RUN CGO_ENABLED=0 GOOS=linux go build -o masterexe ./master

EXPOSE 50051

CMD ["./masterexe"]

# docker network create -d bridge my-net
#docker build --tag master -f Dockerfile.master .
#docker run -p 50051:50051 --network=my-net --name=master master