FROM golang:1.24.2

WORKDIR /chaas

COPY go.mod go.sum ./
RUN go mod download

COPY cache/ ./cache/
COPY master/ ./master/

RUN CGO_ENABLED=0 GOOS=linux go build -o cacheexe ./cache

EXPOSE 50052

CMD ["./cacheexe"]

#docker build --tag cache -f Dockerfile.cache .
#docker run -p 50052:50052 --network=my-net --name=cache cache