apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: cache
        image: chaas-cache:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50052
        env:
        - name: MASTER_HOST
          value: "master"  # Kubernetes DNS name
        - name: MASTER_PORT
          value: "50051"
        - name: CACHE_PORT
          value: "50052"
---
apiVersion: v1
kind: Service
metadata:
  name: cache
spec:
  type: LoadBalancer
  selector:
    app: cache
  ports:
  - port: 50052
    targetPort: 50052 