// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: cache/grpc/cache.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNextNodeIdByKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextNodeIdByKeyRequest) Reset() {
	*x = GetNextNodeIdByKeyRequest{}
	mi := &file_cache_grpc_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextNodeIdByKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextNodeIdByKeyRequest) ProtoMessage() {}

func (x *GetNextNodeIdByKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextNodeIdByKeyRequest.ProtoReflect.Descriptor instead.
func (*GetNextNodeIdByKeyRequest) Descriptor() ([]byte, []int) {
	return file_cache_grpc_cache_proto_rawDescGZIP(), []int{0}
}

func (x *GetNextNodeIdByKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetNextNodeIdByKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextNodeIdByKeyResponse) Reset() {
	*x = GetNextNodeIdByKeyResponse{}
	mi := &file_cache_grpc_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextNodeIdByKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextNodeIdByKeyResponse) ProtoMessage() {}

func (x *GetNextNodeIdByKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextNodeIdByKeyResponse.ProtoReflect.Descriptor instead.
func (*GetNextNodeIdByKeyResponse) Descriptor() ([]byte, []int) {
	return file_cache_grpc_cache_proto_rawDescGZIP(), []int{1}
}

func (x *GetNextNodeIdByKeyResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type UpdateCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCacheRequest) Reset() {
	*x = UpdateCacheRequest{}
	mi := &file_cache_grpc_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCacheRequest) ProtoMessage() {}

func (x *UpdateCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCacheRequest.ProtoReflect.Descriptor instead.
func (*UpdateCacheRequest) Descriptor() ([]byte, []int) {
	return file_cache_grpc_cache_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCacheRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *UpdateCacheRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type UpdateCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCacheResponse) Reset() {
	*x = UpdateCacheResponse{}
	mi := &file_cache_grpc_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCacheResponse) ProtoMessage() {}

func (x *UpdateCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCacheResponse.ProtoReflect.Descriptor instead.
func (*UpdateCacheResponse) Descriptor() ([]byte, []int) {
	return file_cache_grpc_cache_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_cache_grpc_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_cache_grpc_cache_proto_rawDescGZIP(), []int{4}
}

type GetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HashToNodeId  map[string]string      `protobuf:"bytes,1,rep,name=hashToNodeId,proto3" json:"hashToNodeId,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_cache_grpc_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_cache_grpc_cache_proto_rawDescGZIP(), []int{5}
}

func (x *GetStateResponse) GetHashToNodeId() map[string]string {
	if x != nil {
		return x.HashToNodeId
	}
	return nil
}

var File_cache_grpc_cache_proto protoreflect.FileDescriptor

const file_cache_grpc_cache_proto_rawDesc = "" +
	"\n" +
	"\x16cache/grpc/cache.proto\x12\tcacheGrpc\"-\n" +
	"\x19GetNextNodeIdByKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"4\n" +
	"\x1aGetNextNodeIdByKeyResponse\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\"@\n" +
	"\x12UpdateCacheRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x16\n" +
	"\x06nodeId\x18\x02 \x01(\tR\x06nodeId\"/\n" +
	"\x13UpdateCacheResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x11\n" +
	"\x0fGetStateRequest\"\xa6\x01\n" +
	"\x10GetStateResponse\x12Q\n" +
	"\fhashToNodeId\x18\x01 \x03(\v2-.cacheGrpc.GetStateResponse.HashToNodeIdEntryR\fhashToNodeId\x1a?\n" +
	"\x11HashToNodeIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x83\x02\n" +
	"\x05Cache\x12c\n" +
	"\x12GetNextNodeIdByKey\x12$.cacheGrpc.GetNextNodeIdByKeyRequest\x1a%.cacheGrpc.GetNextNodeIdByKeyResponse\"\x00\x12N\n" +
	"\vUpdateCache\x12\x1d.cacheGrpc.UpdateCacheRequest\x1a\x1e.cacheGrpc.UpdateCacheResponse\"\x00\x12E\n" +
	"\bGetState\x12\x1a.cacheGrpc.GetStateRequest\x1a\x1b.cacheGrpc.GetStateResponse\"\x00B\rZ\v/cache/grpcb\x06proto3"

var (
	file_cache_grpc_cache_proto_rawDescOnce sync.Once
	file_cache_grpc_cache_proto_rawDescData []byte
)

func file_cache_grpc_cache_proto_rawDescGZIP() []byte {
	file_cache_grpc_cache_proto_rawDescOnce.Do(func() {
		file_cache_grpc_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_grpc_cache_proto_rawDesc), len(file_cache_grpc_cache_proto_rawDesc)))
	})
	return file_cache_grpc_cache_proto_rawDescData
}

var file_cache_grpc_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cache_grpc_cache_proto_goTypes = []any{
	(*GetNextNodeIdByKeyRequest)(nil),  // 0: cacheGrpc.GetNextNodeIdByKeyRequest
	(*GetNextNodeIdByKeyResponse)(nil), // 1: cacheGrpc.GetNextNodeIdByKeyResponse
	(*UpdateCacheRequest)(nil),         // 2: cacheGrpc.UpdateCacheRequest
	(*UpdateCacheResponse)(nil),        // 3: cacheGrpc.UpdateCacheResponse
	(*GetStateRequest)(nil),            // 4: cacheGrpc.GetStateRequest
	(*GetStateResponse)(nil),           // 5: cacheGrpc.GetStateResponse
	nil,                                // 6: cacheGrpc.GetStateResponse.HashToNodeIdEntry
}
var file_cache_grpc_cache_proto_depIdxs = []int32{
	6, // 0: cacheGrpc.GetStateResponse.hashToNodeId:type_name -> cacheGrpc.GetStateResponse.HashToNodeIdEntry
	0, // 1: cacheGrpc.Cache.GetNextNodeIdByKey:input_type -> cacheGrpc.GetNextNodeIdByKeyRequest
	2, // 2: cacheGrpc.Cache.UpdateCache:input_type -> cacheGrpc.UpdateCacheRequest
	4, // 3: cacheGrpc.Cache.GetState:input_type -> cacheGrpc.GetStateRequest
	1, // 4: cacheGrpc.Cache.GetNextNodeIdByKey:output_type -> cacheGrpc.GetNextNodeIdByKeyResponse
	3, // 5: cacheGrpc.Cache.UpdateCache:output_type -> cacheGrpc.UpdateCacheResponse
	5, // 6: cacheGrpc.Cache.GetState:output_type -> cacheGrpc.GetStateResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cache_grpc_cache_proto_init() }
func file_cache_grpc_cache_proto_init() {
	if File_cache_grpc_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_grpc_cache_proto_rawDesc), len(file_cache_grpc_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cache_grpc_cache_proto_goTypes,
		DependencyIndexes: file_cache_grpc_cache_proto_depIdxs,
		MessageInfos:      file_cache_grpc_cache_proto_msgTypes,
	}.Build()
	File_cache_grpc_cache_proto = out.File
	file_cache_grpc_cache_proto_goTypes = nil
	file_cache_grpc_cache_proto_depIdxs = nil
}
