// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: master/grpc/master.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCacheStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCacheStreamRequest) Reset() {
	*x = GetCacheStreamRequest{}
	mi := &file_master_grpc_master_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCacheStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheStreamRequest) ProtoMessage() {}

func (x *GetCacheStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_grpc_master_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheStreamRequest.ProtoReflect.Descriptor instead.
func (*GetCacheStreamRequest) Descriptor() ([]byte, []int) {
	return file_master_grpc_master_proto_rawDescGZIP(), []int{0}
}

type GetCacheStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCacheStreamResponse) Reset() {
	*x = GetCacheStreamResponse{}
	mi := &file_master_grpc_master_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCacheStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheStreamResponse) ProtoMessage() {}

func (x *GetCacheStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_grpc_master_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheStreamResponse.ProtoReflect.Descriptor instead.
func (*GetCacheStreamResponse) Descriptor() ([]byte, []int) {
	return file_master_grpc_master_proto_rawDescGZIP(), []int{1}
}

func (x *GetCacheStreamResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *GetCacheStreamResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type AddNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodeRequest) Reset() {
	*x = AddNodeRequest{}
	mi := &file_master_grpc_master_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeRequest) ProtoMessage() {}

func (x *AddNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_grpc_master_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeRequest.ProtoReflect.Descriptor instead.
func (*AddNodeRequest) Descriptor() ([]byte, []int) {
	return file_master_grpc_master_proto_rawDescGZIP(), []int{2}
}

func (x *AddNodeRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type AddNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodeResponse) Reset() {
	*x = AddNodeResponse{}
	mi := &file_master_grpc_master_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeResponse) ProtoMessage() {}

func (x *AddNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_grpc_master_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeResponse.ProtoReflect.Descriptor instead.
func (*AddNodeResponse) Descriptor() ([]byte, []int) {
	return file_master_grpc_master_proto_rawDescGZIP(), []int{3}
}

func (x *AddNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RemoveNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeRequest) Reset() {
	*x = RemoveNodeRequest{}
	mi := &file_master_grpc_master_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeRequest) ProtoMessage() {}

func (x *RemoveNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_grpc_master_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeRequest.ProtoReflect.Descriptor instead.
func (*RemoveNodeRequest) Descriptor() ([]byte, []int) {
	return file_master_grpc_master_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RemoveNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeResponse) Reset() {
	*x = RemoveNodeResponse{}
	mi := &file_master_grpc_master_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeResponse) ProtoMessage() {}

func (x *RemoveNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_grpc_master_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeResponse.ProtoReflect.Descriptor instead.
func (*RemoveNodeResponse) Descriptor() ([]byte, []int) {
	return file_master_grpc_master_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateHashRingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumNodes      string                 `protobuf:"bytes,1,opt,name=numNodes,proto3" json:"numNodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHashRingRequest) Reset() {
	*x = CreateHashRingRequest{}
	mi := &file_master_grpc_master_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHashRingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHashRingRequest) ProtoMessage() {}

func (x *CreateHashRingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_grpc_master_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHashRingRequest.ProtoReflect.Descriptor instead.
func (*CreateHashRingRequest) Descriptor() ([]byte, []int) {
	return file_master_grpc_master_proto_rawDescGZIP(), []int{6}
}

func (x *CreateHashRingRequest) GetNumNodes() string {
	if x != nil {
		return x.NumNodes
	}
	return ""
}

type CreateHashRingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHashRingResponse) Reset() {
	*x = CreateHashRingResponse{}
	mi := &file_master_grpc_master_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHashRingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHashRingResponse) ProtoMessage() {}

func (x *CreateHashRingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_grpc_master_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHashRingResponse.ProtoReflect.Descriptor instead.
func (*CreateHashRingResponse) Descriptor() ([]byte, []int) {
	return file_master_grpc_master_proto_rawDescGZIP(), []int{7}
}

func (x *CreateHashRingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_master_grpc_master_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_grpc_master_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_master_grpc_master_proto_rawDescGZIP(), []int{8}
}

type GetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HashToNodeId  map[string]string      `protobuf:"bytes,1,rep,name=hashToNodeId,proto3" json:"hashToNodeId,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_master_grpc_master_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_grpc_master_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_master_grpc_master_proto_rawDescGZIP(), []int{9}
}

func (x *GetStateResponse) GetHashToNodeId() map[string]string {
	if x != nil {
		return x.HashToNodeId
	}
	return nil
}

var File_master_grpc_master_proto protoreflect.FileDescriptor

const file_master_grpc_master_proto_rawDesc = "" +
	"\n" +
	"\x18master/grpc/master.proto\x12\n" +
	"masterGrpc\"\x17\n" +
	"\x15GetCacheStreamRequest\"D\n" +
	"\x16GetCacheStreamResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x16\n" +
	"\x06nodeId\x18\x02 \x01(\tR\x06nodeId\"$\n" +
	"\x0eAddNodeRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\")\n" +
	"\x0fAddNodeResponse\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\"+\n" +
	"\x11RemoveNodeRequest\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\".\n" +
	"\x12RemoveNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x15CreateHashRingRequest\x12\x1a\n" +
	"\bnumNodes\x18\x01 \x01(\tR\bnumNodes\"2\n" +
	"\x16CreateHashRingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x11\n" +
	"\x0fGetStateRequest\"\xa7\x01\n" +
	"\x10GetStateResponse\x12R\n" +
	"\fhashToNodeId\x18\x01 \x03(\v2..masterGrpc.GetStateResponse.HashToNodeIdEntryR\fhashToNodeId\x1a?\n" +
	"\x11HashToNodeIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x9e\x03\n" +
	"\x06Master\x12[\n" +
	"\x0egetCacheStream\x12!.masterGrpc.GetCacheStreamRequest\x1a\".masterGrpc.GetCacheStreamResponse\"\x000\x01\x12D\n" +
	"\aaddNode\x12\x1a.masterGrpc.AddNodeRequest\x1a\x1b.masterGrpc.AddNodeResponse\"\x00\x12M\n" +
	"\n" +
	"removeNode\x12\x1d.masterGrpc.RemoveNodeRequest\x1a\x1e.masterGrpc.RemoveNodeResponse\"\x00\x12Y\n" +
	"\x0ecreateHashRing\x12!.masterGrpc.CreateHashRingRequest\x1a\".masterGrpc.CreateHashRingResponse\"\x00\x12G\n" +
	"\bgetState\x12\x1b.masterGrpc.GetStateRequest\x1a\x1c.masterGrpc.GetStateResponse\"\x00B\x0eZ\f/master/grpcb\x06proto3"

var (
	file_master_grpc_master_proto_rawDescOnce sync.Once
	file_master_grpc_master_proto_rawDescData []byte
)

func file_master_grpc_master_proto_rawDescGZIP() []byte {
	file_master_grpc_master_proto_rawDescOnce.Do(func() {
		file_master_grpc_master_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_master_grpc_master_proto_rawDesc), len(file_master_grpc_master_proto_rawDesc)))
	})
	return file_master_grpc_master_proto_rawDescData
}

var file_master_grpc_master_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_master_grpc_master_proto_goTypes = []any{
	(*GetCacheStreamRequest)(nil),  // 0: masterGrpc.GetCacheStreamRequest
	(*GetCacheStreamResponse)(nil), // 1: masterGrpc.GetCacheStreamResponse
	(*AddNodeRequest)(nil),         // 2: masterGrpc.AddNodeRequest
	(*AddNodeResponse)(nil),        // 3: masterGrpc.AddNodeResponse
	(*RemoveNodeRequest)(nil),      // 4: masterGrpc.RemoveNodeRequest
	(*RemoveNodeResponse)(nil),     // 5: masterGrpc.RemoveNodeResponse
	(*CreateHashRingRequest)(nil),  // 6: masterGrpc.CreateHashRingRequest
	(*CreateHashRingResponse)(nil), // 7: masterGrpc.CreateHashRingResponse
	(*GetStateRequest)(nil),        // 8: masterGrpc.GetStateRequest
	(*GetStateResponse)(nil),       // 9: masterGrpc.GetStateResponse
	nil,                            // 10: masterGrpc.GetStateResponse.HashToNodeIdEntry
}
var file_master_grpc_master_proto_depIdxs = []int32{
	10, // 0: masterGrpc.GetStateResponse.hashToNodeId:type_name -> masterGrpc.GetStateResponse.HashToNodeIdEntry
	0,  // 1: masterGrpc.Master.getCacheStream:input_type -> masterGrpc.GetCacheStreamRequest
	2,  // 2: masterGrpc.Master.addNode:input_type -> masterGrpc.AddNodeRequest
	4,  // 3: masterGrpc.Master.removeNode:input_type -> masterGrpc.RemoveNodeRequest
	6,  // 4: masterGrpc.Master.createHashRing:input_type -> masterGrpc.CreateHashRingRequest
	8,  // 5: masterGrpc.Master.getState:input_type -> masterGrpc.GetStateRequest
	1,  // 6: masterGrpc.Master.getCacheStream:output_type -> masterGrpc.GetCacheStreamResponse
	3,  // 7: masterGrpc.Master.addNode:output_type -> masterGrpc.AddNodeResponse
	5,  // 8: masterGrpc.Master.removeNode:output_type -> masterGrpc.RemoveNodeResponse
	7,  // 9: masterGrpc.Master.createHashRing:output_type -> masterGrpc.CreateHashRingResponse
	9,  // 10: masterGrpc.Master.getState:output_type -> masterGrpc.GetStateResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_master_grpc_master_proto_init() }
func file_master_grpc_master_proto_init() {
	if File_master_grpc_master_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_master_grpc_master_proto_rawDesc), len(file_master_grpc_master_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_master_grpc_master_proto_goTypes,
		DependencyIndexes: file_master_grpc_master_proto_depIdxs,
		MessageInfos:      file_master_grpc_master_proto_msgTypes,
	}.Build()
	File_master_grpc_master_proto = out.File
	file_master_grpc_master_proto_goTypes = nil
	file_master_grpc_master_proto_depIdxs = nil
}
